name: Build and Release Electron App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            args: "--mac dmg"
          - os: windows-latest
            args: "--win nsis"
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2 # v2 is known to work
        with:
          version: 8

      - name: Install root dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build renderer (React + Vite)
        run: |
          cd renderer
          pnpm install --no-frozen-lockfile
          pnpm build
          cd ..

      - name: Compile Electron main process
        run: pnpm tsc -p main

      # ── THIS NEW STEP ─────────────────────────────────────
      - name: Install NSIS (for Windows installer)
        if: matrix.os == 'windows-latest'
        run: choco install nsis --no-progress --confirm

      - name: Build Electron App
        run: npx electron-builder ${{ matrix.args }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional debug: see exactly what’s in dist/
      - name: List dist contents
        run: |
          ls -R dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.zip
