name: Build and Release Electron App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: macos-latest
            args: "--mac dmg"
          - os: windows-latest
            args: "--win nsis"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install root dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build renderer (React + Vite)
        run: |
          cd renderer
          pnpm install --no-frozen-lockfile
          pnpm build
          cd ..

      - name: Compile Electron main process
        run: pnpm tsc -p main

      - name: Build Electron App
        run: |
          rm -rf dist
          npx electron-builder ${{ matrix.args }} --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*
