name: Build and Release Electron App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install root dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install renderer dependencies
        run: |
          cd renderer
          pnpm install --no-frozen-lockfile
          cd ..

      - name: Build renderer (React + Vite)
        run: |
          cd renderer
          pnpm build
          cd ..

      - name: Compile Electron main process
        run: pnpm tsc -p main

      - name: Build Electron App
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            npx electron-builder --mac dmg --publish always
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            npx electron-builder --win nsis --publish always
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*
